#!/usr/bin/env bash
# Copy this file to config.sh and edit the input locations.

PAPER1_REPOSITORY_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)

export PAPER1_ARCHIVE_ROOT="/path/to/paper1-inputs"
export PAPER1_DERIVED_ROOT="${PAPER1_REPOSITORY_ROOT}/work"
export PAPER1_PREPROCESSED_ROOT="${PAPER1_DERIVED_ROOT}"
export PAPER1_FIGURE_ROOT="${PAPER1_DERIVED_ROOT}/figures"
export PAPER1_RAW_MODEL_ROOT="${PAPER1_ARCHIVE_ROOT}/raw_model"
export PAPER1_REFERENCE_ROOT="${PAPER1_ARCHIVE_ROOT}/processed_reference"

export PAPER1_WACCM_LONGRUN_001="${PAPER1_ARCHIVE_ROOT}/WACCM/longrun/run001"
export PAPER1_WACCM_LONGRUN_002="${PAPER1_ARCHIVE_ROOT}/WACCM/longrun/run002"
export PAPER1_WACCM_RESTART_SOURCE="${PAPER1_ARCHIVE_ROOT}/WACCM/restart_source"
export PAPER1_HINDCAST_SOURCE="${PAPER1_ARCHIVE_ROOT}/WACCM/hindcast"
export PAPER1_MARCH_HINDCAST_SOURCE="${PAPER1_ARCHIVE_ROOT}/WACCM/march_hindcast"
export PAPER1_MERRA2_SOURCE="${PAPER1_ARCHIVE_ROOT}/MERRA2/M2I6NPANA"
export PAPER1_MERRA2_Z_SOURCE="${PAPER1_MERRA2_SOURCE}/Z"
export PAPER1_MLS_SOURCE="${PAPER1_ARCHIVE_ROOT}/MLS/Level3_Zonal_v5"
export PAPER1_EXTR_CLOX_SOURCE="${PAPER1_ARCHIVE_ROOT}/WACCM/clox_climatology/CO2x1SmidEmin_yBWCN.cam.h1.0101-0300.CLO.isobar.zm.nc"

export PAPER1_CDO_BIN="cdo"
export PAPER1_MAX_JOBS="4"
