name: paper1-ozone
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.12
  - jupyterlab
  - nbclient
  - nbconvert
  - nbformat
  - numpy
  - pandas
  - xarray
  - dask
  - netcdf4
  - scipy
  - matplotlib
  - pillow
  - cartopy
  - cftime
  - cdo
  - nco
